version: '3'
services:

  db:
    image: postgres:9.6
    container_name: crypz-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=crypz
      - POSTGRES_PASSWORD=crypz
    volumes:
      - ~/Developer/DockerCache/Crypz/:/var/lib/postgresql/data