version: '3'
services:

  db:
    image: postgres:9.6
    container_name: coin-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=coin
      - POSTGRES_PASSWORD=coin
    volumes:
      - ~/Developer/DockerCache/Coin/:/var/lib/postgresql/data